version: '3'
services:
  streamserver-frontend-build:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: >
      /bin/sh -c "corepack enable && \
                  corepack prepare pnpm@8.6.10 --activate && \
                  npm config set registry https://registry.npmmirror.com && \
                  pnpm install --frozen-lockfile && \
                  pnpm build"
